[package]
name = "monkeygang_server"
version = "0.1.0"
edition = "2024"

[dependencies]
native_db = "0.8.1"
native_model = "0.4.2"
once_cell = "1.21.3"
serde = "1.0.219"
tokio = { version = "1.45.1", features = ["full"] }
